//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyricEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LyricEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本：2.1.1
        ///更新日期：2022/7/15
        ///====================================
        ///请在作者的知乎专栏关注软件的【使用说明】。
        ///
        ///如果您在使用过程中发现了任何问题，或者有好的意见或建议，您可以通过以下方式联系我：
        ///
        ///1、发送邮件至 suomikoto@outlook.com
        ///2、在知乎的相关专栏文章下方评论
        ///3、在 GitHub repo 中添加 issue
        ///
        ///随时欢迎您的反馈！
        ///====================================
        ///版本信息：
        ///
        ///2.0.0 (2018/1/1)
        ///1、重写 UI，使界面更加能忍；
        ///2、添加新功能：歌词编辑模式。可以直接查看当前的歌词对应的纯文本；
        ///3、添加细节：展示音频文件的封面，以及一些无聊的界面动画；
        ///4、去除意义不大的多行选择功能（基本用不着，真存在使用情景，歌词编辑模式一般也能解决）；
        ///5、优化下方的编辑区域，上面的歌词列表可以实时更新编辑的文本，不必再按 Enter 键确认修改。
        ///
        ///2.0.4（2022/4/13）
        ///1、调整近似时间的机制，现在将只显示两位毫秒 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
    }
}
